### PR TITLE
fix optional field deserialization

### LINKED ISSUE #13: Optional fields are always set to zeroed values
Hi there,

It looks like borsh-go always sets optional fields to a zero value:

https://github.com/near/borsh-go/blob/master/borsh.go#L223

So a round-trip encode/decode where the fields aren't set in the encoded value ends up with set fields with zero values in the decoded value.

Is this intentional?

### PR DESCRIPTION
**Pull request by holykol**
closes #13

### CODE REVIEW

**Review by omarkilani — APPROVED** [review]
lgtm

**Comment by holykol** [comment]
@ouromoros care to merge?

**Comment by ouromoros** [comment]
Looks great! My account seems to have been kicked out of organization due to policy changes. @frol Will you add me back here?

**Comment by ouromoros** [comment]
Got it. I understand that security is a vital concern in blockchain
projects. No pressure.

Vlad Frolov ***@***.***>于2022年5月17日 周二02:14写道：

**Comment by jchappelow** [comment]
I ran into this issue on the latest tagged release.  Would it be possible to tag a revision that includes this fix?  Thanks.

**Pull request merged**
